logic that does pytest discovery
eleanorjboyd/vscode-python pull request #3
Opened 2022-11-07 23:30 UTC by eleanorjboyd

2022-11-16 23:19 UTC, brettcannon requested changes

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +            test_class_node["children"].append(test_node)
How is this code different than the lines above? Is it just the dict you are working with? If so then I would assign to a new variable that is assigned based on the conditional guard and then uses the same code.

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +            session_children_dict[root_folder_node.get("id_")] = root_folder_node
Should `None` be used as a key in `session_children_dict`, as `dict.get()` will return that if it isn't there? And what if "id_" isn't there? Is `None` a legitimate key?

And assuming `None` is what you want if `"id_"` doesn't exist, then I would not get it twice:

```suggestion
        root_folder_id = root_folder_node.get("id_")
        if root_folder_id not in session_children_dict:
            session_children_dict[root_folder_id] = root_folder_node
```

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +    file_module, file_node, created_files_folders_dict, session
Type the parameters (and everywhere else).

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +    addr = ("localhost", int(testPort))
```suggestion
    addr = "localhost", int(testPort)
```

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +    print("sending post", addr, cwd)
Is this purposefully printed out all the time? Or was this debugging code?

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +        result = s.socket.sendall(request.encode("utf-8"))  # type: ignore
That socket only needs to be open for the send, so you should keep it open for a shorter amount of time. You are also assigning to a variable and then never using it.

```suggestion
    
    data = json.dumps(payload)
    request = f"""POST / HTTP/1.1
Host: localhost:{testPort}
Content-Length: {len(data)}
Content-Type: application/json
Request-uuid: {testuuid}

{data}"""
     with socket_manager.SocketManager(addr) as s:
        s.socket.sendall(request.encode("utf-8"))  # type: ignore
```

2022-11-16 23:19 UTC, brettcannon commented on pythonFiles/pytest-vscode-integration/pytest_vscode_integration.py
> +        result = s.socket.sendall(request.encode("utf-8"))  # type: ignore
And why the `type: ignore` opt-out?

2023-01-04 19:58 UTC, sophacola approved these changes

2023-02-20 01:01 UTC, closed without merging